# Site settings
title: "Dennis's Tennis Lessons"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Dennis's Tennis Lessons"
resume_title:                   "Professional Tennis Instructor"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "dennis.afa@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "757-746-7830"
resume_contact_address:         "Brc"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>My name is Dennis Afanasev and I've been playing tennis since I was four years old. As a junior tennis player, I trained at 
the Junior Tennis Champions Center (JTCC) as well as IMG Academy. I won numerous USTA junior tournaments, having been ranked as high as top 30 nationally for 
boys 14 and under and top 50 nationally for boys 16 and under. In addition, I achieved an International Tennis Federation (ITF) ranking and played numerous professional
tournaments. I played division 1 tennis at the George Washington University, and graduated with a degree in Computer Science. I now work as a Computer Engineer at NASA.
I'm available for private lessons in the Miami Brickell area. If you're interested, please contact me at (757)-746-7830 or email using the Contact Me button below.
</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/jglovier/resume-template"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/dennisafanasev"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
